# Generated by Django 5.2.4 on 2025-08-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="head_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/%Y/%m/%d"),
        ),
    ]
