# Generated by Django 5.2.4 on 2025-08-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_rename_head_image_post_uploaded_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="uploaded_file",
            field=models.FileField(blank=True, null=True, upload_to="files/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="uploaded_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
