# Generated by Django 5.2.4 on 2025-08-04 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_comment_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="comment",
        ),
    ]
